App UI/Models/Login.cs
using System.ComponentModel.DataAnnotations;

namespace AppUI.Models
{
    public class Login
    {
        [Required]
        [EmailAddress]
        public string? Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string? Password { get; set; }
    }
}

App UI/Controllers/EmpInfoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL;
using App_UI.Data;
using App_UI.Models;
using EmpInfo = App_UI.Models.EmpInfo;

namespace App_UI.Controllers
{
    public class EmpInfoesController : Controller
    {
        private readonly App_UIContext _context;

        public EmpInfoesController(App_UIContext context)
        {
            _context = context;
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(EmpInfo model)
        {
            if (ModelState.IsValid)
            {
                // Check if the provided credentials are valid
                var user = await _context.EmpInfo
                    .FirstOrDefaultAsync(u => u.Email == model.Email && u.PassCode == model.PassCode);

                if (user != null)
                {
                    // Redirect to the "Index" page of BlogInfoes after successful login
                    return RedirectToAction("Index", "BlogInfoes");
                }
                else
                {
                    // Set an error message for invalid login attempt
                    TempData["ErrorMessage"] = "Invalid login attempt";
                }
            }

            return View(model);
        }
            // GET: EmpInfoes
            public async Task<IActionResult> Index()
        {
              return _context.EmpInfo != null ? 
                          View(await _context.EmpInfo.ToListAsync()) :
                          Problem("Entity set 'App_UIContext.EmpInfo'  is null.");
        }

        // GET: EmpInfoes/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.EmpInfo == null)
            {
                return NotFound();
            }

            var empInfo = await _context.EmpInfo
                .FirstOrDefaultAsync(m => m.Email == id);
            if (empInfo == null)
            {
                return NotFound();
            }

            return View(empInfo);
        }

        // GET: EmpInfoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: EmpInfoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Email,Name,DateOfJoining,PassCode")] DAL.EmpInfo empInfo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(empInfo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(empInfo);
        }

        // GET: EmpInfoes/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.EmpInfo == null)
            {
                return NotFound();
            }

            var empInfo = await _context.EmpInfo.FindAsync(id);
            if (empInfo == null)
            {
                return NotFound();
            }
            return View(empInfo);
        }

        // POST: EmpInfoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Email,Name,DateOfJoining,PassCode")] DAL.EmpInfo empInfo)
        {
            if (id != empInfo.Email)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(empInfo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmpInfoExists(empInfo.Email))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(empInfo);
        }

        // GET: EmpInfoes/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.EmpInfo == null)
            {
                return NotFound();
            }

            var empInfo = await _context.EmpInfo
                .FirstOrDefaultAsync(m => m.Email == id);
            if (empInfo == null)
            {
                return NotFound();
            }

            return View(empInfo);
        }

        // POST: EmpInfoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.EmpInfo == null)
            {
                return Problem("Entity set 'App_UIContext.EmpInfo'  is null.");
            }
            var empInfo = await _context.EmpInfo.FindAsync(id);
            if (empInfo != null)
            {
                _context.EmpInfo.Remove(empInfo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmpInfoExists(string id)
        {
          return (_context.EmpInfo?.Any(e => e.Email == id)).GetValueOrDefault();
        }
    }
}

App UI/Views/EmpInfoes/Create.cshtml
@model DAL.EmpInfo

@{
    ViewData["Title"] = "Save Employee";
}


<h4>Save Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfJoining" class="control-label"></label>
                <input asp-for="DateOfJoining" class="form-control" />
                <span asp-validation-for="DateOfJoining" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PassCode" class="control-label"></label>
                <input asp-for="PassCode" class="form-control" />
                <span asp-validation-for="PassCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add Employee" class="btn btn-primary"  />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

App UI/Views/EmpInfoes/Delete.cshtml
@model DAL.EmpInfo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EmpInfo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfJoining)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfJoining)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PassCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PassCode)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Email" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

App UI/Views/EmpInfoes/Details.cshtml
@model DAL.EmpInfo

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>EmpInfo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfJoining)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfJoining)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PassCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PassCode)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Email">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

App UI/Views/EmpInfoes/Edit.cshtml
@model DAL.EmpInfo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>EmpInfo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Email" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfJoining" class="control-label"></label>
                <input asp-for="DateOfJoining" class="form-control" />
                <span asp-validation-for="DateOfJoining" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PassCode" class="control-label"></label>
                <input asp-for="PassCode" class="form-control" />
                <span asp-validation-for="PassCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

App UI/Views/EmpInfoes/Index.cshtml
@model IEnumerable<DAL.EmpInfo>

@{
    ViewData["Title"] = "Index";
}

<h1>Employee List</h1>

<p>
    

    <a asp-action="Create" class="create-button"> Add New</a>
</p>
<table class="table" >
    <thead>
        <tr style="background-color: grey;">
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfJoining)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PassCode)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
            <tr style="background-color:lightblue;">
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfJoining)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PassCode)
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.Email" class="red-btn">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Email" class="red-btn">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Email" class="red-btn">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<style>
    .create-button {
        background-color: green;
        color: white; 
        padding: 5px 10px; 
        text-decoration: none; 
        display: inline-block; 
    }
</style>
<style>
    .red-btn {
        background-color: red;
        color: white;
        padding: 5px 10px;
        border: none;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        cursor: pointer;
    }
</style>

App UI/Views/EmpInfoes/Login.cshtml
@model AppUI.Models.EmpLogin

@{
    ViewData["Title"] = "Login";
}

<h2>Employee Login Page</h2>
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        @TempData["ErrorMessage"]
    </div>
}

<form asp-controller="EmpInfoes" asp-action="Login" method="post">
    <div class="form-group">
        <label asp-for="Email">Email:</label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="PassCode">PassCode:</label>
        <input asp-for="PassCode" type="password" class="form-control" />
        <span asp-validation-for="PassCode" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary btn-red">Login</button>
</form>
<style>
    .btn-red {
        background-color: red;
        
    }
</style>